/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BandRouteImport } from './routes/band'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as HotellRouteImport } from './routes/hotell'
import { Route as KartRouteImport } from './routes/kart'
import { Route as OlpriserRouteImport } from './routes/olpriser'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as ReiseRouteImport } from './routes/reise'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SjekklisteRouteImport } from './routes/sjekkliste'
import { Route as VaerRouteImport } from './routes/vaer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandRoute = BandRouteImport.update({
  id: '/band',
  path: '/band',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HotellRoute = HotellRouteImport.update({
  id: '/hotell',
  path: '/hotell',
  getParentRoute: () => rootRouteImport,
} as any)
const KartRoute = KartRouteImport.update({
  id: '/kart',
  path: '/kart',
  getParentRoute: () => rootRouteImport,
} as any)
const OlpriserRoute = OlpriserRouteImport.update({
  id: '/olpriser',
  path: '/olpriser',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const ReiseRoute = ReiseRouteImport.update({
  id: '/reise',
  path: '/reise',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SjekklisteRoute = SjekklisteRouteImport.update({
  id: '/sjekkliste',
  path: '/sjekkliste',
  getParentRoute: () => rootRouteImport,
} as any)
const VaerRoute = VaerRouteImport.update({
  id: '/vaer',
  path: '/vaer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/band': typeof BandRoute
  '/chat': typeof ChatRoute
  '/hotell': typeof HotellRoute
  '/kart': typeof KartRoute
  '/olpriser': typeof OlpriserRoute
  '/program': typeof ProgramRoute
  '/reise': typeof ReiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sjekkliste': typeof SjekklisteRoute
  '/vaer': typeof VaerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/band': typeof BandRoute
  '/chat': typeof ChatRoute
  '/hotell': typeof HotellRoute
  '/kart': typeof KartRoute
  '/olpriser': typeof OlpriserRoute
  '/program': typeof ProgramRoute
  '/reise': typeof ReiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sjekkliste': typeof SjekklisteRoute
  '/vaer': typeof VaerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/band': typeof BandRoute
  '/chat': typeof ChatRoute
  '/hotell': typeof HotellRoute
  '/kart': typeof KartRoute
  '/olpriser': typeof OlpriserRoute
  '/program': typeof ProgramRoute
  '/reise': typeof ReiseRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sjekkliste': typeof SjekklisteRoute
  '/vaer': typeof VaerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/band'
    | '/chat'
    | '/hotell'
    | '/kart'
    | '/olpriser'
    | '/program'
    | '/reise'
    | '/sitemap.xml'
    | '/sjekkliste'
    | '/vaer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/band'
    | '/chat'
    | '/hotell'
    | '/kart'
    | '/olpriser'
    | '/program'
    | '/reise'
    | '/sitemap.xml'
    | '/sjekkliste'
    | '/vaer'
  id:
    | '__root__'
    | '/'
    | '/band'
    | '/chat'
    | '/hotell'
    | '/kart'
    | '/olpriser'
    | '/program'
    | '/reise'
    | '/sitemap.xml'
    | '/sjekkliste'
    | '/vaer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BandRoute: typeof BandRoute
  ChatRoute: typeof ChatRoute
  HotellRoute: typeof HotellRoute
  KartRoute: typeof KartRoute
  OlpriserRoute: typeof OlpriserRoute
  ProgramRoute: typeof ProgramRoute
  ReiseRoute: typeof ReiseRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SjekklisteRoute: typeof SjekklisteRoute
  VaerRoute: typeof VaerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/band': {
      id: '/band'
      path: '/band'
      fullPath: '/band'
      preLoaderRoute: typeof BandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotell': {
      id: '/hotell'
      path: '/hotell'
      fullPath: '/hotell'
      preLoaderRoute: typeof HotellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kart': {
      id: '/kart'
      path: '/kart'
      fullPath: '/kart'
      preLoaderRoute: typeof KartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olpriser': {
      id: '/olpriser'
      path: '/olpriser'
      fullPath: '/olpriser'
      preLoaderRoute: typeof OlpriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reise': {
      id: '/reise'
      path: '/reise'
      fullPath: '/reise'
      preLoaderRoute: typeof ReiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sjekkliste': {
      id: '/sjekkliste'
      path: '/sjekkliste'
      fullPath: '/sjekkliste'
      preLoaderRoute: typeof SjekklisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaer': {
      id: '/vaer'
      path: '/vaer'
      fullPath: '/vaer'
      preLoaderRoute: typeof VaerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BandRoute: BandRoute,
  ChatRoute: ChatRoute,
  HotellRoute: HotellRoute,
  KartRoute: KartRoute,
  OlpriserRoute: OlpriserRoute,
  ProgramRoute: ProgramRoute,
  ReiseRoute: ReiseRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SjekklisteRoute: SjekklisteRoute,
  VaerRoute: VaerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
